name: PLant Blog
description: Writings and Ramblings
url: "https://blog.plbl.net"
markdown: kramdown
plugins_dir:
    - jekyll-relative-links
relative_links:
    enabled: true
    collections: true
include:
  - index.md
theme: jekyll-theme-tactile
excerpt_separator: <!--more-->
